# Generated by Django 6.0 on 2025-12-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerprofile",
            name="role",
            field=models.CharField(
                choices=[("volunteer", "Volunteer"), ("patient", "Patient")],
                default="volunteer",
                max_length=20,
            ),
        ),
    ]
